apiVersion: v1
kind: Service
metadata:
  name: erikson-yallico-17-service
  namespace: erikson-yallico-17-namespace
spec:
  selector:
    app: products-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP